services:
  - type: web
    name: mode-motion
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: "5002"
